
image: docker:20.10.22

variables:
  RUNNER_INFRASTRUCTURE: "shared"

services:
  - name: docker:20.10.22-dind
    alias: docker

sast:
  stage: analysis

include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - analysis

# =============================================================================

build_dev:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'
  tags:
    - docker
    - "${RUNNER_INFRASTRUCTURE}"
  before_script:
    - export BUILD_TAG="$(date -u +%Y%m%d%H%M%Sz)-${CI_COMMIT_SHORT_SHA}"
    - export COMMIT_REF="${CI_COMMIT_BRANCH}"
    - export COMMIT_HASH="${CI_COMMIT_SHORT_SHA}"
    - export BUILD1_NAME="${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}"
  script:
    - echo "${CI_REGISTRY_PASSWORD}" | docker login --password-stdin -u "${CI_REGISTRY_USER}" "${CI_REGISTRY}"
    - docker build --pull --tag "${BUILD1_NAME}:${BUILD_TAG}" --tag "${BUILD1_NAME}:${CI_COMMIT_SHA}" --tag "${BUILD1_NAME}:latest" --build-arg COMMIT_REF=${COMMIT_REF} --build-arg COMMIT_HASH=${COMMIT_HASH} .
    - docker push "${BUILD1_NAME}:${BUILD_TAG}"
    - docker push "${BUILD1_NAME}:latest"
    - docker logout

# =============================================================================

build_tagged:
  stage: build

  rules:
    - if: $CI_COMMIT_TAG =~ /^v?(\d+\.)?(\d+\.)?(\*|\d+)(\+.*?)?$/

  tags:
    - docker
    - "${RUNNER_INFRASTRUCTURE}"

  before_script:
    - export BUILD_TAG="${CI_COMMIT_TAG}"
    - export COMMIT_REF="${CI_COMMIT_TAG}"
    - export COMMIT_HASH="${CI_COMMIT_SHORT_SHA}"
    - export BUILD1_NAME="${CI_REGISTRY_IMAGE}"
    - export BUILD2_NAME="${DOCKERHUB_REGISTRY}/${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME//docker-}"

  script:
    - echo "${CI_REGISTRY_PASSWORD}" | docker login --password-stdin -u "${CI_REGISTRY_USER}" "${CI_REGISTRY}"
    - docker build --pull --tag "${BUILD1_NAME}:${BUILD_TAG}" --tag "${BUILD1_NAME}:latest" --build-arg COMMIT_REF=${COMMIT_REF} --build-arg COMMIT_HASH=${COMMIT_HASH} .
    - docker push "${BUILD1_NAME}:${BUILD_TAG}"
    - docker push "${BUILD1_NAME}:latest"
    - docker logout

    - echo "${DOCKERHUB_PASSWORD}" | docker login --password-stdin -u "${DOCKERHUB_USERNAME}" "${DOCKERHUB_REGISTRY}"
    - docker build --pull --tag "${BUILD2_NAME}:${BUILD_TAG}" --tag "${BUILD2_NAME}:latest" --build-arg COMMIT_REF=${COMMIT_REF} --build-arg COMMIT_HASH=${COMMIT_HASH} .
    - docker push "${BUILD2_NAME}:${BUILD_TAG}"
    - docker push "${BUILD2_NAME}:latest"
    - docker logout
