
image: docker:20.10.16

include:

variables:
  RUNNER_INFRASTRUCTURE: "shared"

services:
  - name: docker:20.10.16-dind
    alias: docker

stages:
  - build
  - test
  - deploy
  - analysis

# =============================================================================

build-dev:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'
  variables:
    COMMIT_REF: "${CI_COMMIT_SHORT_SHA}"
    COMMIT_HASH: "${CI_COMMIT_SHORT_SHA}"
  tags:
    - docker
    - "${RUNNER_INFRASTRUCTURE}"
  before_script:
    - export RUNNER_TIMESTAMP="$(date -u +%Y%m%d%H%M%Sz)"
  script:
    - export BUILD_TAG="${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}:${RUNNER_TIMESTAMP}-${COMMIT_REF}"
    - echo "BUILD_TAG = ${BUILD_TAG}"
    - echo "${CI_REGISTRY_PASSWORD}" | docker login --password-stdin -u "${CI_REGISTRY_USER}" "${CI_REGISTRY}"
    - docker build --pull --tag "${BUILD_TAG}" --build-arg COMMIT_REF=${COMMIT_REF} --build-arg COMMIT_HASH=${COMMIT_HASH} .
    - docker push "${BUILD_TAG}"
    - docker logout

# =============================================================================

build-latest:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == 'latest'
  variables:
    COMMIT_REF: "${CI_COMMIT_BRANCH}"
    COMMIT_HASH: "${CI_COMMIT_SHORT_SHA}"
  tags:
    - docker
    - "${RUNNER_INFRASTRUCTURE}"
  script:
    - export BUILD_TAG="${CI_REGISTRY_IMAGE}:${COMMIT_REF}"
    - echo "BUILD_TAG = ${BUILD_TAG}"
    - echo "${CI_REGISTRY_PASSWORD}" | docker login --password-stdin -u "${CI_REGISTRY_USER}" "${CI_REGISTRY}"
    - docker build --pull --tag "${BUILD_TAG}" --build-arg COMMIT_REF=${COMMIT_REF} --build-arg COMMIT_HASH=${COMMIT_HASH} .
    - docker push "${BUILD_TAG}"
    - docker logout

    - export BUILD_TAG="${DOCKERHUB_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME//docker-}:${COMMIT_REF}"
    - echo "BUILD_TAG = ${BUILD_TAG}"
    - echo "${DOCKERHUB_PASSWORD}" | docker login --password-stdin -u "${DOCKERHUB_USERNAME}" "${DOCKERHUB_REGISTRY}"
    - docker build --pull --tag "${BUILD_TAG}" --build-arg COMMIT_REF=${COMMIT_REF} --build-arg COMMIT_HASH=${COMMIT_HASH} .
    - docker push "${BUILD_TAG}"
    - docker logout

# =============================================================================

build-tagged:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
  variables:
    COMMIT_REF: "${CI_COMMIT_TAG}"
    COMMIT_HASH: "${CI_COMMIT_SHORT_SHA}"
  tags:
    - docker
    - "${RUNNER_INFRASTRUCTURE}"
  script:
    - export BUILD_TAG="${CI_REGISTRY_IMAGE}:${COMMIT_REF}"
    - echo "BUILD_TAG = ${BUILD_TAG}"
    - echo "${CI_REGISTRY_PASSWORD}" | docker login --password-stdin -u "${CI_REGISTRY_USER}" "${CI_REGISTRY}"
    - docker build --pull --tag "${BUILD_TAG}" --build-arg COMMIT_REF=${COMMIT_REF} --build-arg COMMIT_HASH=${COMMIT_HASH} .
    - docker push "${BUILD_TAG}"
    - docker logout

    - export BUILD_TAG="${DOCKERHUB_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME//docker-}:${COMMIT_REF}"
    - echo "BUILD_TAG = ${BUILD_TAG}"
    - echo "${DOCKERHUB_PASSWORD}" | docker login --password-stdin -u "${DOCKERHUB_USERNAME}" "${DOCKERHUB_REGISTRY}"
    - docker build --pull --tag "${BUILD_TAG}" --build-arg COMMIT_REF=${COMMIT_REF} --build-arg COMMIT_HASH=${COMMIT_HASH} .
    - docker push "${BUILD_TAG}"
    - docker logout
