version: "3"

services:

  externalhost01:
    image: docker.io/threatpatrols/docker-sshjumphost
    restart: unless-stopped
    expose:
      - 22/tcp
    ports:
      - 22222:22/tcp
    networks:
      - awesome_network
    environment:
      SSH_USERNAME: "awesome"
      SSH_AUTHORIZED_KEYS: "sk-ecdsa-sha2-nistp256@openssh.com xxxxxxxxxxxxxxxxxxxxxxxxx"

  internalhost01:
    image: docker.io/threatpatrols/docker-sshjumphost
    restart: unless-stopped
    expose:
      - 22/tcp
    volumes:
      - "/home/awesome/.ssh/authorized_keys:/data/userkeys/awesome_authorized_keys:ro"
    networks:
      - awesome_network
    environment:
      SSH_USERNAME: "awesome"
      SSH_SHELL: "/bin/ash"
      SSH_AUTHORIZED_KEYS: "/data/userkeys/awesome_authorized_keys"

networks:
  awesome_network:
    driver: bridge
